### ISSUE TITLE
Ghosts Animations Calls localhost:8065 Instead of mattermost:8065

### ISSUE THREAD

**Issue by dh4340** [cmu-sei/GHOSTS#425]
# Description

When using Ghosts animations, it is attempting to connect to localhost:8065 instead of mattermost:8065. The job configuration allows for this change, but the logs still show localhost being called, resulting in a failure to connect.

## Steps to Reproduce

Use Ghosts animations in the application.
Check the job configuration to ensure it is set to mattermost:8065.
Review the logs for the connection attempt.

## Expected Behavior

The application should call mattermost:8065 as configured, allowing a successful connection.

## Actual Behavior

The logs indicate that the application is calling localhost:8065, which fails to connect. I have confirmed that mattermost:8065 works from within the container, but localhost does not.

### Additional Information:

This configuration is challenging to get working correctly with container with a default of localhost.

**Comment by dh4340** [comment]
![Screenshot 2024-10-09 at 14 14 38](https://github.com/user-attachments/assets/5b4cbc11-4166-49b1-adeb-cb696a87831c)
![Screenshot 2024-10-09 at 14 15 37](https://github.com/user-attachments/assets/592a0528-ca2a-4fc2-ab40-3b61f769eba3)

**Comment by sei-dupdyke** [comment]
Oof. I'll look to fix the config this week, sorry. What version of the container is this?

**Comment by sei-dupdyke** [comment]
Container 8.2.4 fixes this issue. LMK if you see anything else with chat that is unexpected please.

**Comment by dh4340** [comment]
This is still happening on the latest version 8.2.499.0

![Screenshot 2024-10-10 at 09 09 03](https://github.com/user-attachments/assets/e091ac9f-4681-4400-8913-7f92d911c168)

**Comment by sei-dupdyke** [comment]
Oof, my bad. Fixed in 8.2.5.1 or latest container. Sorry about that.

**Comment by dh4340** [comment]
Just seen top work fixing it, I was about to do it for you.

**Comment by sei-dupdyke** [comment]
The animation classes take two different config files - the standard and whatever you override from the page. I had them confused.

**Comment by dh4340** [comment]
Sorry noticed another issue with regards to the same piece, now working but you missed off a /
![Screenshot 2024-10-10 at 17 08 08](https://github.com/user-attachments/assets/ad48f6a4-3474-4ac3-bec8-eed946144838)
